- Added WEB supporting
NikolayFatkullin/SpringIntro pull request #3
Opened 2021-02-10 18:40 UTC by NikolayFatkullin

2021-02-10 19:46 UTC, Fedich09 approved these changes

2021-02-10 19:46 UTC, Fedich09 commented on src/main/java/spring/intro/controller/UserController.java
> +    @GetMapping("/")
```suggestion
    @GetMapping
```

2021-02-11 08:34 UTC, dmytro-hryhoruk requested changes

2021-02-11 08:34 UTC, dmytro-hryhoruk commented on src/main/java/spring/intro/dao/impl/UserDaoImpl.java
> +            return Optional.of(session.get(User.class, id));
there is no point in using Optional in such way. What will happen if the null will be passed to the method of()?

2021-02-11 08:34 UTC, dmytro-hryhoruk commented on src/main/java/spring/intro/dto/UserResponseDto.java
> +    private String name;
let's add id too

2021-02-11 08:34 UTC, dmytro-hryhoruk commented on src/main/java/spring/intro/service/impl/UserServiceImpl.java
> +    }
service should return an object or throw an exception(you can use orElseThrow for this) but not Optional

2021-02-11 11:54 UTC, dmytro-hryhoruk approved these changes

2021-02-11 13:08 UTC, merged